# Generated by Django 2.1.1 on 2018-10-07 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_author_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('post_comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.FileField(upload_to='author_pic/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.article'),
        ),
    ]
