# Generated by Django 2.1.2 on 2018-10-13 20:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20181014_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_comment',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
