# Generated by Django 2.1.2 on 2018-10-13 20:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20181014_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
