# Generated by Django 2.1.2 on 2018-10-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20181014_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
